package com.export.xml.sample;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
@XmlRootElement(name = "Report")
@XmlAccessorType(XmlAccessType.FIELD)
public class Report {
	private String CASH_LBRT_ID;
	private String CASH_LBRT_NUMBER;
	private String CASH_LBRT_COMPANY_ID;
	private String CASH_LBRT_TRX_NUMBER;
	private String CASH_LBRT_TYPE;
	private String CASH_LBRT_TRX_DATE;
	private double CASH_LBRT_AMOUNT;
	private double CASH_LBRT_INV_AMOUNT;
	private String CASH_LBRT_BILL_TO_CUSTOMER_ID;
	private String CASH_LBRT_BILL_TO_SITE_USE_ID;
	private String CASH_LBRT_CHECK_NUMBER;
	private String CASH_LBRT_ACCP_ID;
	private String CASH_LBRT_EFFECTIVE_START_DATE;
	private String CASH_LBRT_EFFECTIVE_END_DATE;
	private String CASH_LBRT_CREATION_DATE;
	private String CASH_LBRT_CREATED_BY;
	private String CASH_LBRT_LAST_UPDATED_DATE;
	private String CASH_LBRT_LAST_UPDATED_BY;
	private String CASH_LBRT_ATTRIBUTE1;
	private String CASH_LBRT_ATTRIBUTE2;
	private String CASH_LBRT_ATTRIBUTE3;
	private String CASH_LBRT_ATTRIBUTE4;
	private String CASH_LBRT_ATTRIBUTE5;
	private String CASH_LBRT_ATTRIBUTE6;
	private String CASH_LBRT_ATTRIBUTE7;
	private String CASH_LBRT_ATTRIBUTE8;
	private String CASH_LBRT_ATTRIBUTE9;
	private String CASH_LBRT_ATTRIBUTE10;
	private String CASH_LBRT_LOAD_TYPE;
	private String CASH_LBRT_MATCHED_AMT;
	private String CASH_LBRT_MATCHED_DATE;
	private String CASH_LBRT_LBOX_NUMBER;
	private String CASH_LBRT_UNMATCHED_AMT;
	private String CASH_LBRT_UNIDFED_AMT;
	private String CASH_LBRT_BALANCE;
	private String CASH_LBRT_PO_NUMBER;
	private String CASH_LBRT_SO_NUMBER;
	private String CASH_LBRT_CUS_MICR;
	private String CASH_LBRT_CUS_MATCH_SRC;
	private String CASH_LBRT_STATUS;
	private String CASH_LBRT_PYMNT_TYPE;
	private String CASH_LBRT_BALANCE_AMOUNT;
	private String CASH_LBRT_BALANCE_DUE;
	private String CASH_LBRT_CHECK_AMOUNT;
	private String CASH_LBRT_DISCOUNT_AMOUNT;
	private String CASH_LBRT_RULE;
	private String CASH_LBRT_CUS_NAME;
	private String CASH_LBRT_ABA_RT_NUM;
	private String CASH_LBRT_ACC_NUM;
	private String CASH_LBRT_REMITTER_NAME;
	private String CASH_LBRT_TOT_DISCOUNT;

	public String getCASH_LBRT_ID() {
		return CASH_LBRT_ID;
	}

	public void setCASH_LBRT_ID(String cASH_LBRT_ID) {
		CASH_LBRT_ID = cASH_LBRT_ID;
	}

	public String getCASH_LBRT_NUMBER() {
		return CASH_LBRT_NUMBER;
	}

	public void setCASH_LBRT_NUMBER(String cASH_LBRT_NUMBER) {
		CASH_LBRT_NUMBER = cASH_LBRT_NUMBER;
	}

	public String getCASH_LBRT_COMPANY_ID() {
		return CASH_LBRT_COMPANY_ID;
	}

	public void setCASH_LBRT_COMPANY_ID(String cASH_LBRT_COMPANY_ID) {
		CASH_LBRT_COMPANY_ID = cASH_LBRT_COMPANY_ID;
	}

	public String getCASH_LBRT_TRX_NUMBER() {
		return CASH_LBRT_TRX_NUMBER;
	}

	public void setCASH_LBRT_TRX_NUMBER(String cASH_LBRT_TRX_NUMBER) {
		CASH_LBRT_TRX_NUMBER = cASH_LBRT_TRX_NUMBER;
	}

	public String getCASH_LBRT_TYPE() {
		return CASH_LBRT_TYPE;
	}

	public void setCASH_LBRT_TYPE(String cASH_LBRT_TYPE) {
		CASH_LBRT_TYPE = cASH_LBRT_TYPE;
	}

	public String getCASH_LBRT_TRX_DATE() {
		return CASH_LBRT_TRX_DATE;
	}

	public void setCASH_LBRT_TRX_DATE(String cASH_LBRT_TRX_DATE) {
		CASH_LBRT_TRX_DATE = cASH_LBRT_TRX_DATE;
	}

	public double getCASH_LBRT_AMOUNT() {
		return CASH_LBRT_AMOUNT;
	}

	public void setCASH_LBRT_AMOUNT(double cASH_LBRT_AMOUNT) {
		CASH_LBRT_AMOUNT = cASH_LBRT_AMOUNT;
	}

	public double getCASH_LBRT_INV_AMOUNT() {
		return CASH_LBRT_INV_AMOUNT;
	}

	public void setCASH_LBRT_INV_AMOUNT(double cASH_LBRT_INV_AMOUNT) {
		CASH_LBRT_INV_AMOUNT = cASH_LBRT_INV_AMOUNT;
	}

	public String getCASH_LBRT_BILL_TO_CUSTOMER_ID() {
		return CASH_LBRT_BILL_TO_CUSTOMER_ID;
	}

	public void setCASH_LBRT_BILL_TO_CUSTOMER_ID(
			String cASH_LBRT_BILL_TO_CUSTOMER_ID) {
		CASH_LBRT_BILL_TO_CUSTOMER_ID = cASH_LBRT_BILL_TO_CUSTOMER_ID;
	}

	public String getCASH_LBRT_BILL_TO_SITE_USE_ID() {
		return CASH_LBRT_BILL_TO_SITE_USE_ID;
	}

	public void setCASH_LBRT_BILL_TO_SITE_USE_ID(
			String cASH_LBRT_BILL_TO_SITE_USE_ID) {
		CASH_LBRT_BILL_TO_SITE_USE_ID = cASH_LBRT_BILL_TO_SITE_USE_ID;
	}

	public String getCASH_LBRT_CHECK_NUMBER() {
		return CASH_LBRT_CHECK_NUMBER;
	}

	public void setCASH_LBRT_CHECK_NUMBER(String cASH_LBRT_CHECK_NUMBER) {
		CASH_LBRT_CHECK_NUMBER = cASH_LBRT_CHECK_NUMBER;
	}

	public String getCASH_LBRT_ACCP_ID() {
		return CASH_LBRT_ACCP_ID;
	}

	public void setCASH_LBRT_ACCP_ID(String cASH_LBRT_ACCP_ID) {
		CASH_LBRT_ACCP_ID = cASH_LBRT_ACCP_ID;
	}

	public String getCASH_LBRT_EFFECTIVE_START_DATE() {
		return CASH_LBRT_EFFECTIVE_START_DATE;
	}

	public void setCASH_LBRT_EFFECTIVE_START_DATE(
			String cASH_LBRT_EFFECTIVE_START_DATE) {
		CASH_LBRT_EFFECTIVE_START_DATE = cASH_LBRT_EFFECTIVE_START_DATE;
	}

	public String getCASH_LBRT_EFFECTIVE_END_DATE() {
		return CASH_LBRT_EFFECTIVE_END_DATE;
	}

	public void setCASH_LBRT_EFFECTIVE_END_DATE(
			String cASH_LBRT_EFFECTIVE_END_DATE) {
		CASH_LBRT_EFFECTIVE_END_DATE = cASH_LBRT_EFFECTIVE_END_DATE;
	}

	public String getCASH_LBRT_CREATION_DATE() {
		return CASH_LBRT_CREATION_DATE;
	}

	public void setCASH_LBRT_CREATION_DATE(String cASH_LBRT_CREATION_DATE) {
		CASH_LBRT_CREATION_DATE = cASH_LBRT_CREATION_DATE;
	}

	public String getCASH_LBRT_CREATED_BY() {
		return CASH_LBRT_CREATED_BY;
	}

	public void setCASH_LBRT_CREATED_BY(String cASH_LBRT_CREATED_BY) {
		CASH_LBRT_CREATED_BY = cASH_LBRT_CREATED_BY;
	}

	public String getCASH_LBRT_LAST_UPDATED_DATE() {
		return CASH_LBRT_LAST_UPDATED_DATE;
	}

	public void setCASH_LBRT_LAST_UPDATED_DATE(
			String cASH_LBRT_LAST_UPDATED_DATE) {
		CASH_LBRT_LAST_UPDATED_DATE = cASH_LBRT_LAST_UPDATED_DATE;
	}

	public String getCASH_LBRT_LAST_UPDATED_BY() {
		return CASH_LBRT_LAST_UPDATED_BY;
	}

	public void setCASH_LBRT_LAST_UPDATED_BY(String cASH_LBRT_LAST_UPDATED_BY) {
		CASH_LBRT_LAST_UPDATED_BY = cASH_LBRT_LAST_UPDATED_BY;
	}

	public String getCASH_LBRT_ATTRIBUTE1() {
		return CASH_LBRT_ATTRIBUTE1;
	}

	public void setCASH_LBRT_ATTRIBUTE1(String cASH_LBRT_ATTRIBUTE1) {
		CASH_LBRT_ATTRIBUTE1 = cASH_LBRT_ATTRIBUTE1;
	}

	public String getCASH_LBRT_ATTRIBUTE2() {
		return CASH_LBRT_ATTRIBUTE2;
	}

	public void setCASH_LBRT_ATTRIBUTE2(String cASH_LBRT_ATTRIBUTE2) {
		CASH_LBRT_ATTRIBUTE2 = cASH_LBRT_ATTRIBUTE2;
	}

	public String getCASH_LBRT_ATTRIBUTE3() {
		return CASH_LBRT_ATTRIBUTE3;
	}

	public void setCASH_LBRT_ATTRIBUTE3(String cASH_LBRT_ATTRIBUTE3) {
		CASH_LBRT_ATTRIBUTE3 = cASH_LBRT_ATTRIBUTE3;
	}

	public String getCASH_LBRT_ATTRIBUTE4() {
		return CASH_LBRT_ATTRIBUTE4;
	}

	public void setCASH_LBRT_ATTRIBUTE4(String cASH_LBRT_ATTRIBUTE4) {
		CASH_LBRT_ATTRIBUTE4 = cASH_LBRT_ATTRIBUTE4;
	}

	public String getCASH_LBRT_ATTRIBUTE5() {
		return CASH_LBRT_ATTRIBUTE5;
	}

	public void setCASH_LBRT_ATTRIBUTE5(String cASH_LBRT_ATTRIBUTE5) {
		CASH_LBRT_ATTRIBUTE5 = cASH_LBRT_ATTRIBUTE5;
	}

	public String getCASH_LBRT_ATTRIBUTE6() {
		return CASH_LBRT_ATTRIBUTE6;
	}

	public void setCASH_LBRT_ATTRIBUTE6(String cASH_LBRT_ATTRIBUTE6) {
		CASH_LBRT_ATTRIBUTE6 = cASH_LBRT_ATTRIBUTE6;
	}

	public String getCASH_LBRT_ATTRIBUTE7() {
		return CASH_LBRT_ATTRIBUTE7;
	}

	public void setCASH_LBRT_ATTRIBUTE7(String cASH_LBRT_ATTRIBUTE7) {
		CASH_LBRT_ATTRIBUTE7 = cASH_LBRT_ATTRIBUTE7;
	}

	public String getCASH_LBRT_ATTRIBUTE8() {
		return CASH_LBRT_ATTRIBUTE8;
	}

	public void setCASH_LBRT_ATTRIBUTE8(String cASH_LBRT_ATTRIBUTE8) {
		CASH_LBRT_ATTRIBUTE8 = cASH_LBRT_ATTRIBUTE8;
	}

	public String getCASH_LBRT_ATTRIBUTE9() {
		return CASH_LBRT_ATTRIBUTE9;
	}

	public void setCASH_LBRT_ATTRIBUTE9(String cASH_LBRT_ATTRIBUTE9) {
		CASH_LBRT_ATTRIBUTE9 = cASH_LBRT_ATTRIBUTE9;
	}

	public String getCASH_LBRT_ATTRIBUTE10() {
		return CASH_LBRT_ATTRIBUTE10;
	}

	public void setCASH_LBRT_ATTRIBUTE10(String cASH_LBRT_ATTRIBUTE10) {
		CASH_LBRT_ATTRIBUTE10 = cASH_LBRT_ATTRIBUTE10;
	}

	public String getCASH_LBRT_LOAD_TYPE() {
		return CASH_LBRT_LOAD_TYPE;
	}

	public void setCASH_LBRT_LOAD_TYPE(String cASH_LBRT_LOAD_TYPE) {
		CASH_LBRT_LOAD_TYPE = cASH_LBRT_LOAD_TYPE;
	}

	public String getCASH_LBRT_MATCHED_AMT() {
		return CASH_LBRT_MATCHED_AMT;
	}

	public void setCASH_LBRT_MATCHED_AMT(String cASH_LBRT_MATCHED_AMT) {
		CASH_LBRT_MATCHED_AMT = cASH_LBRT_MATCHED_AMT;
	}

	public String getCASH_LBRT_MATCHED_DATE() {
		return CASH_LBRT_MATCHED_DATE;
	}

	public void setCASH_LBRT_MATCHED_DATE(String cASH_LBRT_MATCHED_DATE) {
		CASH_LBRT_MATCHED_DATE = cASH_LBRT_MATCHED_DATE;
	}

	public String getCASH_LBRT_LBOX_NUMBER() {
		return CASH_LBRT_LBOX_NUMBER;
	}

	public void setCASH_LBRT_LBOX_NUMBER(String cASH_LBRT_LBOX_NUMBER) {
		CASH_LBRT_LBOX_NUMBER = cASH_LBRT_LBOX_NUMBER;
	}

	public String getCASH_LBRT_UNMATCHED_AMT() {
		return CASH_LBRT_UNMATCHED_AMT;
	}

	public void setCASH_LBRT_UNMATCHED_AMT(String cASH_LBRT_UNMATCHED_AMT) {
		CASH_LBRT_UNMATCHED_AMT = cASH_LBRT_UNMATCHED_AMT;
	}

	public String getCASH_LBRT_UNIDFED_AMT() {
		return CASH_LBRT_UNIDFED_AMT;
	}

	public void setCASH_LBRT_UNIDFED_AMT(String cASH_LBRT_UNIDFED_AMT) {
		CASH_LBRT_UNIDFED_AMT = cASH_LBRT_UNIDFED_AMT;
	}

	public String getCASH_LBRT_BALANCE() {
		return CASH_LBRT_BALANCE;
	}

	public void setCASH_LBRT_BALANCE(String cASH_LBRT_BALANCE) {
		CASH_LBRT_BALANCE = cASH_LBRT_BALANCE;
	}

	public String getCASH_LBRT_PO_NUMBER() {
		return CASH_LBRT_PO_NUMBER;
	}

	public void setCASH_LBRT_PO_NUMBER(String cASH_LBRT_PO_NUMBER) {
		CASH_LBRT_PO_NUMBER = cASH_LBRT_PO_NUMBER;
	}

	public String getCASH_LBRT_SO_NUMBER() {
		return CASH_LBRT_SO_NUMBER;
	}

	public void setCASH_LBRT_SO_NUMBER(String cASH_LBRT_SO_NUMBER) {
		CASH_LBRT_SO_NUMBER = cASH_LBRT_SO_NUMBER;
	}

	public String getCASH_LBRT_CUS_MICR() {
		return CASH_LBRT_CUS_MICR;
	}

	public void setCASH_LBRT_CUS_MICR(String cASH_LBRT_CUS_MICR) {
		CASH_LBRT_CUS_MICR = cASH_LBRT_CUS_MICR;
	}

	public String getCASH_LBRT_CUS_MATCH_SRC() {
		return CASH_LBRT_CUS_MATCH_SRC;
	}

	public void setCASH_LBRT_CUS_MATCH_SRC(String cASH_LBRT_CUS_MATCH_SRC) {
		CASH_LBRT_CUS_MATCH_SRC = cASH_LBRT_CUS_MATCH_SRC;
	}

	public String getCASH_LBRT_STATUS() {
		return CASH_LBRT_STATUS;
	}

	public void setCASH_LBRT_STATUS(String cASH_LBRT_STATUS) {
		CASH_LBRT_STATUS = cASH_LBRT_STATUS;
	}

	public String getCASH_LBRT_PYMNT_TYPE() {
		return CASH_LBRT_PYMNT_TYPE;
	}

	public void setCASH_LBRT_PYMNT_TYPE(String cASH_LBRT_PYMNT_TYPE) {
		CASH_LBRT_PYMNT_TYPE = cASH_LBRT_PYMNT_TYPE;
	}

	public String getCASH_LBRT_BALANCE_AMOUNT() {
		return CASH_LBRT_BALANCE_AMOUNT;
	}

	public void setCASH_LBRT_BALANCE_AMOUNT(String cASH_LBRT_BALANCE_AMOUNT) {
		CASH_LBRT_BALANCE_AMOUNT = cASH_LBRT_BALANCE_AMOUNT;
	}

	public String getCASH_LBRT_BALANCE_DUE() {
		return CASH_LBRT_BALANCE_DUE;
	}

	public void setCASH_LBRT_BALANCE_DUE(String cASH_LBRT_BALANCE_DUE) {
		CASH_LBRT_BALANCE_DUE = cASH_LBRT_BALANCE_DUE;
	}

	public String getCASH_LBRT_CHECK_AMOUNT() {
		return CASH_LBRT_CHECK_AMOUNT;
	}

	public void setCASH_LBRT_CHECK_AMOUNT(String cASH_LBRT_CHECK_AMOUNT) {
		CASH_LBRT_CHECK_AMOUNT = cASH_LBRT_CHECK_AMOUNT;
	}

	public String getCASH_LBRT_DISCOUNT_AMOUNT() {
		return CASH_LBRT_DISCOUNT_AMOUNT;
	}

	public void setCASH_LBRT_DISCOUNT_AMOUNT(String cASH_LBRT_DISCOUNT_AMOUNT) {
		CASH_LBRT_DISCOUNT_AMOUNT = cASH_LBRT_DISCOUNT_AMOUNT;
	}

	public String getCASH_LBRT_RULE() {
		return CASH_LBRT_RULE;
	}

	public void setCASH_LBRT_RULE(String cASH_LBRT_RULE) {
		CASH_LBRT_RULE = cASH_LBRT_RULE;
	}

	public String getCASH_LBRT_CUS_NAME() {
		return CASH_LBRT_CUS_NAME;
	}

	public void setCASH_LBRT_CUS_NAME(String cASH_LBRT_CUS_NAME) {
		CASH_LBRT_CUS_NAME = cASH_LBRT_CUS_NAME;
	}

	public String getCASH_LBRT_ABA_RT_NUM() {
		return CASH_LBRT_ABA_RT_NUM;
	}

	public void setCASH_LBRT_ABA_RT_NUM(String cASH_LBRT_ABA_RT_NUM) {
		CASH_LBRT_ABA_RT_NUM = cASH_LBRT_ABA_RT_NUM;
	}

	public String getCASH_LBRT_ACC_NUM() {
		return CASH_LBRT_ACC_NUM;
	}

	public void setCASH_LBRT_ACC_NUM(String cASH_LBRT_ACC_NUM) {
		CASH_LBRT_ACC_NUM = cASH_LBRT_ACC_NUM;
	}

	public String getCASH_LBRT_REMITTER_NAME() {
		return CASH_LBRT_REMITTER_NAME;
	}

	public void setCASH_LBRT_REMITTER_NAME(String cASH_LBRT_REMITTER_NAME) {
		CASH_LBRT_REMITTER_NAME = cASH_LBRT_REMITTER_NAME;
	}

	public String getCASH_LBRT_TOT_DISCOUNT() {
		return CASH_LBRT_TOT_DISCOUNT;
	}

	public void setCASH_LBRT_TOT_DISCOUNT(String cASH_LBRT_TOT_DISCOUNT) {
		CASH_LBRT_TOT_DISCOUNT = cASH_LBRT_TOT_DISCOUNT;
	}

	public Report(String cASH_LBRT_ID, String cASH_LBRT_NUMBER,
			String cASH_LBRT_COMPANY_ID, String cASH_LBRT_TRX_NUMBER,
			String cASH_LBRT_TYPE, String cASH_LBRT_TRX_DATE,
			double cASH_LBRT_AMOUNT, double cASH_LBRT_INV_AMOUNT,
			String cASH_LBRT_BILL_TO_CUSTOMER_ID,
			String cASH_LBRT_BILL_TO_SITE_USE_ID,
			String cASH_LBRT_CHECK_NUMBER, String cASH_LBRT_ACCP_ID,
			String cASH_LBRT_EFFECTIVE_START_DATE,
			String cASH_LBRT_EFFECTIVE_END_DATE,
			String cASH_LBRT_CREATION_DATE, String cASH_LBRT_CREATED_BY,
			String cASH_LBRT_LAST_UPDATED_DATE,
			String cASH_LBRT_LAST_UPDATED_BY, String cASH_LBRT_ATTRIBUTE1,
			String cASH_LBRT_ATTRIBUTE2, String cASH_LBRT_ATTRIBUTE3,
			String cASH_LBRT_ATTRIBUTE4, String cASH_LBRT_ATTRIBUTE5,
			String cASH_LBRT_ATTRIBUTE6, String cASH_LBRT_ATTRIBUTE7,
			String cASH_LBRT_ATTRIBUTE8, String cASH_LBRT_ATTRIBUTE9,
			String cASH_LBRT_ATTRIBUTE10, String cASH_LBRT_LOAD_TYPE,
			String cASH_LBRT_MATCHED_AMT, String cASH_LBRT_MATCHED_DATE,
			String cASH_LBRT_LBOX_NUMBER, String cASH_LBRT_UNMATCHED_AMT,
			String cASH_LBRT_UNIDFED_AMT, String cASH_LBRT_BALANCE,
			String cASH_LBRT_PO_NUMBER, String cASH_LBRT_SO_NUMBER,
			String cASH_LBRT_CUS_MICR, String cASH_LBRT_CUS_MATCH_SRC,
			String cASH_LBRT_STATUS, String cASH_LBRT_PYMNT_TYPE,
			String cASH_LBRT_BALANCE_AMOUNT, String cASH_LBRT_BALANCE_DUE,
			String cASH_LBRT_CHECK_AMOUNT, String cASH_LBRT_DISCOUNT_AMOUNT,
			String cASH_LBRT_RULE, String cASH_LBRT_CUS_NAME,
			String cASH_LBRT_ABA_RT_NUM, String cASH_LBRT_ACC_NUM,
			String cASH_LBRT_REMITTER_NAME, String cASH_LBRT_TOT_DISCOUNT) {
		super();
		CASH_LBRT_ID = cASH_LBRT_ID;
		CASH_LBRT_NUMBER = cASH_LBRT_NUMBER;
		CASH_LBRT_COMPANY_ID = cASH_LBRT_COMPANY_ID;
		CASH_LBRT_TRX_NUMBER = cASH_LBRT_TRX_NUMBER;
		CASH_LBRT_TYPE = cASH_LBRT_TYPE;
		CASH_LBRT_TRX_DATE = cASH_LBRT_TRX_DATE;
		CASH_LBRT_AMOUNT = cASH_LBRT_AMOUNT;
		CASH_LBRT_INV_AMOUNT = cASH_LBRT_INV_AMOUNT;
		CASH_LBRT_BILL_TO_CUSTOMER_ID = cASH_LBRT_BILL_TO_CUSTOMER_ID;
		CASH_LBRT_BILL_TO_SITE_USE_ID = cASH_LBRT_BILL_TO_SITE_USE_ID;
		CASH_LBRT_CHECK_NUMBER = cASH_LBRT_CHECK_NUMBER;
		CASH_LBRT_ACCP_ID = cASH_LBRT_ACCP_ID;
		CASH_LBRT_EFFECTIVE_START_DATE = cASH_LBRT_EFFECTIVE_START_DATE;
		CASH_LBRT_EFFECTIVE_END_DATE = cASH_LBRT_EFFECTIVE_END_DATE;
		CASH_LBRT_CREATION_DATE = cASH_LBRT_CREATION_DATE;
		CASH_LBRT_CREATED_BY = cASH_LBRT_CREATED_BY;
		CASH_LBRT_LAST_UPDATED_DATE = cASH_LBRT_LAST_UPDATED_DATE;
		CASH_LBRT_LAST_UPDATED_BY = cASH_LBRT_LAST_UPDATED_BY;
		CASH_LBRT_ATTRIBUTE1 = cASH_LBRT_ATTRIBUTE1;
		CASH_LBRT_ATTRIBUTE2 = cASH_LBRT_ATTRIBUTE2;
		CASH_LBRT_ATTRIBUTE3 = cASH_LBRT_ATTRIBUTE3;
		CASH_LBRT_ATTRIBUTE4 = cASH_LBRT_ATTRIBUTE4;
		CASH_LBRT_ATTRIBUTE5 = cASH_LBRT_ATTRIBUTE5;
		CASH_LBRT_ATTRIBUTE6 = cASH_LBRT_ATTRIBUTE6;
		CASH_LBRT_ATTRIBUTE7 = cASH_LBRT_ATTRIBUTE7;
		CASH_LBRT_ATTRIBUTE8 = cASH_LBRT_ATTRIBUTE8;
		CASH_LBRT_ATTRIBUTE9 = cASH_LBRT_ATTRIBUTE9;
		CASH_LBRT_ATTRIBUTE10 = cASH_LBRT_ATTRIBUTE10;
		CASH_LBRT_LOAD_TYPE = cASH_LBRT_LOAD_TYPE;
		CASH_LBRT_MATCHED_AMT = cASH_LBRT_MATCHED_AMT;
		CASH_LBRT_MATCHED_DATE = cASH_LBRT_MATCHED_DATE;
		CASH_LBRT_LBOX_NUMBER = cASH_LBRT_LBOX_NUMBER;
		CASH_LBRT_UNMATCHED_AMT = cASH_LBRT_UNMATCHED_AMT;
		CASH_LBRT_UNIDFED_AMT = cASH_LBRT_UNIDFED_AMT;
		CASH_LBRT_BALANCE = cASH_LBRT_BALANCE;
		CASH_LBRT_PO_NUMBER = cASH_LBRT_PO_NUMBER;
		CASH_LBRT_SO_NUMBER = cASH_LBRT_SO_NUMBER;
		CASH_LBRT_CUS_MICR = cASH_LBRT_CUS_MICR;
		CASH_LBRT_CUS_MATCH_SRC = cASH_LBRT_CUS_MATCH_SRC;
		CASH_LBRT_STATUS = cASH_LBRT_STATUS;
		CASH_LBRT_PYMNT_TYPE = cASH_LBRT_PYMNT_TYPE;
		CASH_LBRT_BALANCE_AMOUNT = cASH_LBRT_BALANCE_AMOUNT;
		CASH_LBRT_BALANCE_DUE = cASH_LBRT_BALANCE_DUE;
		CASH_LBRT_CHECK_AMOUNT = cASH_LBRT_CHECK_AMOUNT;
		CASH_LBRT_DISCOUNT_AMOUNT = cASH_LBRT_DISCOUNT_AMOUNT;
		CASH_LBRT_RULE = cASH_LBRT_RULE;
		CASH_LBRT_CUS_NAME = cASH_LBRT_CUS_NAME;
		CASH_LBRT_ABA_RT_NUM = cASH_LBRT_ABA_RT_NUM;
		CASH_LBRT_ACC_NUM = cASH_LBRT_ACC_NUM;
		CASH_LBRT_REMITTER_NAME = cASH_LBRT_REMITTER_NAME;
		CASH_LBRT_TOT_DISCOUNT = cASH_LBRT_TOT_DISCOUNT;
	}

	public Report() {
		super();
		// TODO Auto-generated constructor stub
	}

}
